#include <ibeamlab/inverse_model.h>
#include <ibeamlab/parameter.h>
#include "onnx_model.h"
#include <unordered_map>
#include <stdexcept>
namespace ibeamlab::inference {
struct InverseModel::Impl{detail::OnnxModel model;explicit Impl(model::ModelPackage p,InferenceOptions o):model(std::move(p),o){if(model.metadata().modelType!=ibeamlab::model::ModelType::Inverse)throw std::invalid_argument("InverseModel requires an inverse package");}};
InverseModel::InverseModel(const std::filesystem::path&p,InferenceOptions o):InverseModel(model::ModelPackage::open(p),o){}InverseModel::InverseModel(model::ModelPackage p,InferenceOptions o):impl_(std::make_unique<Impl>(std::move(p),o)){}InverseModel::~InverseModel()=default;InverseModel::InverseModel(InverseModel&&)noexcept=default;InverseModel&InverseModel::operator=(InverseModel&&)noexcept=default;
std::vector<InverseResult>InverseModel::predict(const std::vector<std::vector<simulator::Spectrum>>&batch)const{const auto&m=impl_->model.metadata().inverse;preprocessing::Matrix rows;for(const auto&sample:batch){std::unordered_map<std::string,const simulator::Spectrum*>byLabel;for(const auto&s:sample)if(!byLabel.emplace(s.label,&s).second)throw std::invalid_argument("duplicate spectrum: "+s.label);std::vector<float>row;for(const auto&spec:m.inputSpectra){const auto found=byLabel.find(spec.label);if(found==byLabel.end()||found->second->counts.size()!=spec.length)throw std::invalid_argument("missing or incorrectly sized spectrum: "+spec.label);row.insert(row.end(),found->second->counts.begin(),found->second->counts.end());}rows.push_back(std::move(row));}const auto values=impl_->model.run(rows);std::vector<InverseResult>results;for(const auto&row:values){simulator::SimulationInput materialized{m.sampleTemplate,m.setupTemplate};InverseResult result;for(std::size_t i=0;i<m.outputParameters.size();++i){const auto&p=m.outputParameters[i];const auto value=row[i];if(value<p.lowerBound||value>p.upperBound)throw std::runtime_error("inverse output outside bounds: "+p.name);parameter::write(materialized,p.target,value);result.parameters.push_back({p.name,value,p.unit});}materialized.sample.validate();result.sample=std::move(materialized.sample);results.push_back(std::move(result));}return results;}
}
