#include <ibeamlab/sample_toml.h>
#include <toml++/toml.hpp>
#include <sstream>
#include <stdexcept>

namespace ibeamlab::sample { namespace {
double number(const toml::table& t,const char* key){auto value=t[key].value<double>();if(!value)throw std::runtime_error(std::string("missing numeric field: ")+key);return *value;}
std::string text(const toml::table& t,const char* key){auto value=t[key].value<std::string>();if(!value)throw std::runtime_error(std::string("missing string field: ")+key);return *value;}
}
std::string toToml(const SampleModel& sample){sample.validate();toml::array layers;for(const auto& layer:sample.layers){toml::array species;for(const auto& item:layer.species){toml::array isotopes;for(const auto& isotope:item.isotopes)isotopes.push_back(toml::table{{"mass_number",isotope.massNumber},{"exact_mass",isotope.exactMass},{"fraction",isotope.fraction}});species.push_back(toml::table{{"element",item.element},{"concentration",item.concentration},{"isotopes",std::move(isotopes)}});}layers.push_back(toml::table{{"thickness",layer.thickness},{"roughness",layer.roughness},{"porosity_fraction",layer.porosityFraction},{"pore_diameter",layer.poreDiameter},{"species",std::move(species)}});}toml::table root{{"format","ibeamlab.sample"},{"format_version",1},{"layers",std::move(layers)}};std::ostringstream output;output<<root;return output.str();}
SampleModel sampleModelFromToml(const std::string& source){const auto root=toml::parse(source);if(root["format"].value_or<std::string>("")!="ibeamlab.sample"||root["format_version"].value_or(0)!=1)throw std::runtime_error("unsupported sample TOML format");SampleModel sample;const auto* layers=root["layers"].as_array();if(!layers)throw std::runtime_error("sample TOML has no layers");for(const auto& layerNode:*layers){const auto* t=layerNode.as_table();if(!t)throw std::runtime_error("layer must be a table");Layer layer{number(*t,"thickness"),number(*t,"roughness"),number(*t,"porosity_fraction"),number(*t,"pore_diameter"),{}};const auto* species=(*t)["species"].as_array();if(!species)throw std::runtime_error("layer has no species");for(const auto& speciesNode:*species){const auto* s=speciesNode.as_table();if(!s)throw std::runtime_error("species must be a table");Species item{text(*s,"element"),number(*s,"concentration"),{}};if(const auto* isotopes=(*s)["isotopes"].as_array())for(const auto& isotopeNode:*isotopes){const auto* i=isotopeNode.as_table();if(!i)throw std::runtime_error("isotope must be a table");item.isotopes.push_back({(*i)["mass_number"].value_or<std::int32_t>(0),(*i)["exact_mass"].value_or(0.0),number(*i,"fraction")});}layer.species.push_back(std::move(item));}sample.layers.push_back(std::move(layer));}sample.validate();return sample;}
std::string toToml(const ExperimentalSetup& setup){setup.validate();toml::array detectors;for(const auto& d:setup.detectors)detectors.push_back(toml::table{{"label",d.label},{"particle",d.beam.particle},{"beam_energy",d.beam.energy},{"beam_spread",d.beam.spread},{"calibration_linear",d.calibrationLinear},{"particles_sr",d.particlesSr},{"calibration_offset",d.calibrationOffset},{"calibration_quadratic",d.calibrationQuadratic},{"resolution",d.resolution},{"real_time",d.realTime},{"live_time",d.liveTime},{"info",d.info}});toml::table root{{"format","ibeamlab.experimental-setup"},{"format_version",1},{"detectors",std::move(detectors)}};std::ostringstream output;output<<root;return output.str();}
ExperimentalSetup experimentalSetupFromToml(const std::string& source){const auto root=toml::parse(source);if(root["format"].value_or<std::string>("")!="ibeamlab.experimental-setup"||root["format_version"].value_or(0)!=1)throw std::runtime_error("unsupported setup TOML format");ExperimentalSetup setup;const auto* detectors=root["detectors"].as_array();if(!detectors)throw std::runtime_error("setup TOML has no detectors");for(const auto& node:*detectors){const auto* d=node.as_table();if(!d)throw std::runtime_error("detector must be a table");setup.detectors.push_back({text(*d,"label"),{text(*d,"particle"),number(*d,"beam_energy"),number(*d,"beam_spread")},number(*d,"calibration_linear"),number(*d,"particles_sr"),number(*d,"calibration_offset"),number(*d,"calibration_quadratic"),number(*d,"resolution"),number(*d,"real_time"),number(*d,"live_time"),text(*d,"info")});}setup.validate();return setup;}
}
